routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware'=>['auth','2fa']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    
    Route::get('/offer-name', 'OfferController@offerNameList')->name('offer-name');

    Route::get('/search/user/aweber', 'HomeController@getUserFromAweber')->name('aweber-search-user');

    Route::get('/leads', 'LeadsController@viewSearch')->name('leads');
    Route::get('/doSearch', 'LeadsController@doSearch')->name('do-search');
    Route::any('/allData', 'LeadsController@allData')->name('allData');
    Route::post('/leads/delete', 'LeadsController@delete')->name('delete-leads');
    Route::get('/leads/edit', 'LeadsController@edit')->name('edit-leads');
    Route::post('/leads/edit', 'LeadsController@update')->name('update-leads');
    
    Route::any('/manual-leads', 'ManualLeadsController@index')->name('manual-leads');
    Route::any('/manual-leads/sync', 'ManualLeadsController@sync')->name('manual-leads-sync');
    Route::any('/manual-leads/clean', 'ManualLeadsController@cleanRecords')->name('manual-leads-clean');
    Route::get('/manual-leads/all-data', 'ManualLeadsController@allData')->name('manual-leads-allData');
    Route::get('/manual-leads/edit', 'ManualLeadsController@edit')->name('manual-leads-edit');
    Route::post('/manual-leads/edit', 'ManualLeadsController@update')->name('update-manual-leads');
    Route::post('/manual-leads/delete', 'ManualLeadsController@delete')->name('delete-manual-leads');


    Route::get('/flux-offers/list', 'FluxOfferController@list')->name('flux-offers-list');
    Route::resource('flux-offers', 'FluxOfferController');

    Route::post('/otp/generate', 'OTPController@generate')->name('otp-generate');
    Route::post('/otp/verify', 'OTPController@verify')->name('otp-verify');

    Route::get('/offer-condition/editOfferCondition', 'OfferConditionController@editOfferCondition')->name('edit-offerCondition');
    Route::get('/offer-condition/list', 'OfferConditionController@list')->name('offer-condition-list');
    Route::resource('offer-condition', 'OfferConditionController');


    // NETWORK

    Route::get('/edit/network', 'NetworkController@edit')->name('edit.network');
    Route::post('/update/network', 'NetworkController@updateNetwork')->name('update.network');
    Route::get('/network/list', 'NetworkController@list')->name('network.list');
    Route::resource('network', 'NetworkController');
    // END

    // NETWORK PLATFORM

    Route::get('/edit/platform', 'NetworkPlatformController@edit')->name('edit.platform');
    Route::post('/update/platform', 'NetworkPlatformController@updatePlatform')->name('update.platform');
    Route::get('/platform/list', 'NetworkPlatformController@list')->name('platform.list');
    Route::resource('platform', 'NetworkPlatformController');
    // END

    // USER

    Route::get('/edit/user', 'UserController@edit')->name('edit.user');
    Route::post('/update/user', 'UserController@updateUser')->name('update.user');
    Route::get('/user/list', 'UserController@list')->name('user.list');
    Route::resource('user', 'UserController');
    // END


});

Route::get('/complete-registration', 'Auth\RegisterController@completeRegistration');

Route::post('/2fa', function () {
    return redirect('/');
})->name('2fa')->middleware('2fa');


Route::get('/re-authenticate', 'HomeController@reauthenticate')->name('re-authenticate');

Route::permanentRedirect('/home', '/dashboard', 301);
Route::permanentRedirect('/', '/login', 301);

Route::group(['prefix'=>'offers'], function () {

        Route::post('/edit', 'OfferController@update')->name('update-offers');
        Route::get('/edit', 'OfferController@edit')->name('offers-edit');
        Route::get('/list', 'OfferController@offerList')->name('offers-list');
        Route::any('/all-data', 'OfferController@allData')->name('offers-allData');
        Route::get('/networks/list', 'OfferController@getNetworkList');

        Route::get('/sync/account/cake', 'OfferController@syncCakeOffers')->name('sync-account-cake');
        Route::get('/sync/offers/cake', 'OfferController@syncCakeOfferStatus')->name('sync-offers-cake');

        Route::get('/sync/account/hasoffer', 'OfferController@syncHasOffers')->name('sync-account-hasoffer');
        Route::get('/sync/offers/hasoffer', 'OfferController@syncHasOfferStatus')->name('sync-offers-hasoffer');

        Route::get('/sync/account/everflow', 'OfferController@syncEverflow')->name('sync-account-everflow');

        Route::get('/status/{type}/{id}/', 'OfferController@offerStatus');

        Route::post('/status/array', 'OfferController@offerStatusArray')->name('offer-status-array'); // Added App\Http\Middleware\VerifyCsrfToken
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'google2fa_secret',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'google2fa_secret',
    ];

     /**
     * Ecrypt the user's google_2fa secret.
     *
     * @param  string  $value
     * @return string
     */
    public function setGoogle2faSecretAttribute($value)
    {
         $this->attributes['google2fa_secret'] = encrypt($value);
    }

    /**
     * Decrypt the user's google_2fa secret.
     *
     * @param  string  $value
     * @return string
     */
    public function getGoogle2faSecretAttribute($value)
    {
        return decrypt($value);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;
use Validator;
use Auth;
class UserController extends Controller
{
	public function __construct()
	{
		$this->middleware('role:admin');
	}

    public function index()
    {   
    	
        $title = "Manage Users";
        return view('user.index', compact('title'));
    }


    public function list()
    {
        $rows = User::all();
        
        return view('user.ajax.list', compact('rows'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
         $validator = Validator::make($request->all(), [
                'name' => 'required',               
                'email' => 'required|string|email|unique:users',
                'password' => 'required|string|min:6|confirmed',
                'active' => 'required'

         ]);

        
        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->first()]);
        }

        $User = new User;
        
        $User->name = $request->input('name');
        
        $User->email = $request->input('email');
        $User->password = bcrypt($request->input('password'));
        $User->active = $request->input('active');

        $User->save(); 
        $User->assignRole($request->input('role'));
        return response()->json(['success'=>'true','message'=>'User has been added successfully']);
    }

    public function edit(Request $request)
    {   
       
        $id = $request->id;       
        $user = User::where('id',$id)->first();

        return view('user.ajax.edit',compact('user'));
        
    }
    
    public function updateUser(Request $request)
    {   
       $validator = Validator::make($request->all(), [
                'name' => 'required',
                
                'email' => 'required|string|email|unique:users,email,'.$request->id,
                 'active' => 'required'
               

         ]);

        
        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->first()]);
        }

        $User = User::find($request->id);
        
        $User->name = $request->input('name');
         
        $User->email = $request->input('email');
        $password = $request->input('password');
        
        if(!empty($password))
            $User->password = bcrypt($password);
        
        $User->active = $request->input('active');
        $User->save(); 
        $User->syncRoles($request->input('role'));


        return response()->json(['success'=>'true','message'=>'User has been updated successfully']);
        
    }

    public  function destroy(User $user)
    {
        $id = $user->id;
        $User = User::findOrFail($id);
        $User->delete();
        flash('User Deleted Successfully')->success();
        return redirect()->back();
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title', $title)
@section('content')
<style>
	.table {font-size: 12px;}
</style>


	<div class="text-right">
		<a href="javascript:void(0)" class="btn btn-info" id="addUser">+ Add User</a>
	</div>
	<br>
	<div class="row">
		<div class="col-lg-12">

			<div class="card shadow-base bd-0">
			    <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
			      	<h6 class="card-title tx-uppercase tx-12 mg-b-0">User List</h6>
			    </div><!-- card-header -->
			    <div class="card-body justify-content-between align-items-center">
			  @include('flash::message')
			 <div id="success"></div>
			  <div id="result">
			  		
			  </div>
			 </div>
			</div>
		</div>
	</div>

<!-- Edit Modal -->
<div class="modal fade" id="editUserModal">
  <div class="modal-dialog">
    <div class="modal-content" id="editResult">



    </div>
  </div>
</div>

<!-- add Modal -->
<div class="modal fade" id="UserModal">
  <div class="modal-dialog">
    <div class="modal-content">

      	{!! Form::open(['class'=>'form-material','id'=>'addUserForm']) !!}
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add New User</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
      	  <div id="errors"></div>
      	  <div class="row">
      	    <div class="col-md-12">
      	      <div class="form-group">
      	        <label>Name</label>
      	        {!! Form::text('name',null,['class'=>'form-control form-control-line']) !!}
      	      </div>
      	    </div>
      	     
      	  <div class="col-md-12">
      	  <div class="form-group">
      	    <label>Email</label>
      	    {!! Form::text('email',null,['class'=>'form-control form-control-line','id'=>'email']) !!}
      	  </div>
      	</div>
      	  <div class="col-md-6">
      	  <div class="form-group">
      	    <label>Password</label>
      	    {!! Form::password('password',['class'=>'form-control form-control-line','id'=>'password']) !!}
      	  </div>
      	</div>
      	  <div class="col-md-6">
      	  <div class="form-group">
      	    <label>Confirm Password</label>
      	    
      	    {!! Form::password('password_confirmation',['class'=>'form-control form-control-line', 'id'=>"password-confirm"]) !!}
      	  </div>
      	</div>
      	  <div class="col-md-6">
      	  <div class="form-group">
      	    <label>Role</label>

      	    {!! Form::select('role',getRoles(),null,['class'=>'form-control form-control-line']) !!}
      	  </div>
      	</div>
      	  <div class="col-md-6">
      	   <div class="form-group" style="margin-top:40px">

      	    <label>Active</label>
      	    {!! Form::radio('active',1,true) !!}
      	    <label>Inactive</label>
      	    {!! Form::radio('active',0,null) !!}
      	  </div> 
      	  </div>
      	</div>
      <!-- Modal footer -->


    </div>
      <div class="modal-footer">
        <input type="submit" value="Submit" class="btn btn-info">
      </div>

      {!! Form::close() !!}
  </div>
</div>



@endsection




@push('scripts')

<script>
	  
	  $(document).ready(function(){

	    getUser();
	    $("#addUser").click(function(){
	      $("#errors").text("");
	      $("#UserModal").modal();
	    });






	  $('#addUserForm').submit(function (data) {


	  	$.post("{{ route('user.store') }}",$(this).serialize(), function(data){


	      if(data.errors)
	      {
	        $("#errors").html('<div class="alert alert-danger">'+data.errors+'</div>');

	      }else{

	        if(data.success == 'true')
	        {
	          $("#UserModal").modal('hide');
	          getUser();
	          $("#success").html('<div class="alert alert-success">'+data.message+'</div>');
	          $('#addUserForm')[0].reset();

	        }else{

	          $("#errors").html('<div class="alert alert-danger">Something went wrong</div>');

	        }

	      }


	      })

	  		return false;

	  });

	  });

	  function getUser()
	  {
	    $("#result").html("Loading...");
	    $.get('{{ route("user.list") }}',function(data){

	     $("#result").html(data);

	     $('#userTable').DataTable({
	     			responsive: true,
	     	          language: {
	     	            searchPlaceholder: 'Search...',
	     	            sSearch: '',
	     	            
	     	          }
	     });

	     deleteConfirm();

	   });
	  }

	  function edit(id)
	  {
	   $("#editUserModal").modal();

	   $.get('{{ route("edit.user") }}',{id:id},function(data){
	     $("#editResult").html(data);
	     $('#userTable').DataTable();
	   });

	 }

	 function deleteConfirm()
	 {
	  $('.deleteFrm').on('submit', function () {

	    var title = $(this).find('.btn-delete').attr('data-title');

	    var poll = confirm("Confirm Delete ?");

	    if(poll)
	    {
	      return true;
	    }
	    else
	    {
	      return false;
	    }

	  })
	}

</script>

@endpush